name: simajalengka_app
description: Online Digital Media Majalengka

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # Intl
  intl: ^0.16.1
  # Webview
  webview_flutter: ^1.0.5
  # HTTP
  http: ^0.12.2
  # Provider
  provider: ^4.3.2+2
  # Local Notification
  flutter_local_notifications: ^3.0.1+2
  # Background Process
  android_alarm_manager: ^0.4.5+17
  # RxDart
  rxdart: ^0.24.1
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.0
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Launcher Icons
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_launch.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon_launch.png
    - assets/fonts/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Libre Franklin
      fonts:
        - asset: assets/fonts/LibreFranklin-Black.ttf
          weight: 900
        - asset: assets/fonts/LibreFranklin-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LibreFranklin-Bold.ttf
          weight: 700
        - asset: assets/fonts/LibreFranklin-Medium.ttf
          weight: 600
        - asset: assets/fonts/LibreFranklin-Regular.ttf
          weight: 500
        - asset: assets/fonts/LibreFranklin-Light.ttf
          weight: 400
        - asset: assets/fonts/LibreFranklin-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/LibreFranklin-Thin.ttf
          weight: 200
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Black.ttf
          weight: 900
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather-Regular.ttf
          weight: 500
        - asset: assets/fonts/Merriweather-Light.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
